---
title: "Managing research with GitHub"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE
)
```

Shortlink to here: http://bit.ly/xxx-link-to-decide

[\@mauro_lepore](https://twitter.com/mauro_lepore)  
2018-08-29, 1-2:30 pm ([compare with your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Managing+research+with+GitHub&iso=20180829T13&p1=263&ah=1&am=30))  
NMNH, Director's Conference Room - 430  
You don't need to register -- Just show up.   


### Description

In this meetup I'll show how you can use GitHub to manage your research. Although I'll assume you have no previous experience with GitHub, I'll move quite fast. After my demo you may not be able to immediately reproduce what I did but you will know what features of GitHub you want to learn more. I'll share slides with links to resources to help yourself whenever you practice on your own time.

### Tentative outline

* Create a research organization to manage multiple projects.
* Create an organization-wide webpage.
* Create private and public projects (folders) to store almost anything.
* Create a project-specific webpage.
* Add colleagues to your organization and organize them in teams to work on specific projects.
* Track conversations for each project.
* Manage notifications.
* Clone and connect a GitHub project with RStudio.
